# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4dbf719036592e48bfbfe1b4b25ec6729c00b91c6cadd99f083a0938163d139bed04957afec7a3da7f6e46808a1703b8e2697124d123149ac9877d8a8b89da54

test:
  secret_key_base: ec82d500430a8ed9570debc33e533489aee9b1f4b22d9cac5bb174053404eea629e7e1b6e92bbc4b06a283b9dd7b29f2f22c48f0e8d1fb36fc1507be49422bbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
